version: "3.9"

services:
  jenkins:
    image: jenkins-android-fastlane
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
