name: Build

on:
  push:
    branches: [ main, kmp_with_analyze_tools ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: macos-13
    env:
      STORE_PASSWORD:  ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS:       ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD:    ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Create local.properties with real values
        run: |
          cat <<EOF > local.properties
          CLOUD_URL=${{ secrets.CLOUD_URL }}
          JDBC_URL=${{ secrets.JDBC_URL }}
          DRIVER_CLASS_NAME=${{ secrets.DRIVER_CLASS_NAME }}
          DB_USER_NAME=${{ secrets.DB_USER_NAME }}
          DB_USER_PASSWORD=${{ secrets.DB_USER_PASSWORD }}
          EOF
      - name: Decode Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > $HOME/ci-release-key.jks
          echo "STORE_FILE=$HOME/ci-release-key.jks" >> $GITHUB_ENV

      #baseline profile
      - name: Generate & merge baseline-profile
        uses: reactivecircus/android-emulator-runner@v2.30.0
        timeout-minutes: 30
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_4
          disk-size: 4096M
          disable-animations: true
          emulator-options: >
            -no-window -noaudio -no-boot-anim
            -gpu swiftshader_indirect
            -no-snapshot
            -grpc-use-token=no
            
            pre-emulator-launch-script: |
            echo "Restarting adb *before* emulator starts..."
            adb kill-server || true
            adb start-server
            
            script: |
            adb wait-for-device
            
            echo "=== Check env ==="
            adb devices -l
            adb shell getprop | head -n 20
            echo "================="
            
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
            
            ./gradlew :baselineprofile:updateBaselineProfile
            
            adb logcat -d > baselineprofile-emulator.log
      - name: Commit & push
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/kmp_with_ci_cd'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add baselineprofile/src/main/baseline-prof.txt
          git commit -m "ci: update baseline profile" || echo "No changes"
          git push || true
      #sonar
      - name: Build and analyze with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            --info \
            -x assembleDebug -x packageDebug -x validateSigningDebug