name: Build

on:
  push:
    branches: [ main, kmp_with_analyze_tools ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: macos-13
    env:
      STORE_PASSWORD:  ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS:       ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD:    ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Create local.properties with real values
        run: |
          cat <<EOF > local.properties
          CLOUD_URL=${{ secrets.CLOUD_URL }}
          JDBC_URL=${{ secrets.JDBC_URL }}
          DRIVER_CLASS_NAME=${{ secrets.DRIVER_CLASS_NAME }}
          DB_USER_NAME=${{ secrets.DB_USER_NAME }}
          DB_USER_PASSWORD=${{ secrets.DB_USER_PASSWORD }}
          EOF
      - name: Decode Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > $HOME/ci-release-key.jks
          echo "STORE_FILE=$HOME/ci-release-key.jks" >> $GITHUB_ENV

      #macrobenchmark
      - name: Run Macrobenchmark (emulator-runner • ARM image)
        uses: reactivecircus/android-emulator-runner@v2.30.0
        timeout-minutes: 25
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_4
          disable-animations: true
          emulator-options: -no-window -noaudio -no-boot-anim -no-snapshot -grpc-use-token false
          script: ./gradlew :benchmark:connectedCheck
      - name: Upload macrobenchmark result
        uses: actions/upload-artifact@v4
        with:
          name: macrobenchmark-${{ github.sha }}
          path: benchmark/build/outputs/connected_android_test_additional_output/**/benchmarkData.json
      - name: Download baseline macrobenchmark
        if: github.event_name == 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: macrobenchmark-main
          path: baseline_macro
      - name: Check macrobenchmark regressions
        if: github.event_name == 'pull_request'
        run: |
          CUR=$(find benchmark/build/outputs/connected_android_test_additional_output -name benchmarkData.json | head -n1)
          BASE=baseline_macro/benchmarkData.json
          ./gradlew :benchmark:compareBenchmark \
            -PbaselineFile=$BASE \
            -PcurrentFile=$CUR \
            -PthresholdPercent=15
          echo "Macrobenchmark ✅"
      - name: Promote macrobenchmark baseline
        if: github.ref == 'refs/heads/main'
        run: |
          CUR=$(find benchmark/build/outputs/connected_android_test_additional_output -name benchmarkData.json | head -n1)
          cp "$CUR" macro-baseline.json
      - name: Upload new macrobaseline artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: macrobenchmark-main
          path: macro-baseline.json
          retention-days: 30
      #sonar
      - name: Build and analyze with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            --info \
            -x assembleDebug -x packageDebug -x validateSigningDebug